### PR TITLE
add Sinhala lang

### PR DESCRIPTION
**Pull request by nimeshc64**
Sinhala, Sinhalese lang [SriLanka]

### CODE REVIEW

**Comment by nimeshc64** [comment]
any update

**Comment by t1m0n** [comment]
@nimeshc64 Hi! Thanks for your PR, could you please change base branch to `v3` and refactor locale file according to the [ new syntax](https://github.com/t1m0n/air-datepicker/blob/v3/src/locale/en.js)?

**Comment by t1m0n** [comment]
Please note, that date format tokens has been changed since v3, you could read about them [on documentation page](https://air-datepicker.com/docs?scrollTo=dateFormat)

**Comment by nimeshc64** [comment]
sure.
add pr to v3
https://github.com/t1m0n/air-datepicker/pull/464

**Pull request closed without merging**
